# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Foroozandeh group blog
description: >- # this means to ignore newlines until "baseurl:"
  A blog for the Foroozandeh group at Oxford.
baseurl: ""   # the subpath of your site, e.g. /blog
url: "https://foroozandehgroup.github.io"
github_username:  foroozandehgroup
subscribe: false

# Build settings
# theme: jekyll-theme-hamilton  # Hamilton is not natively supported by GH pages...
plugins:
  - jekyll-feed
  - jekyll-theme-hamilton
remote_theme: ngzhio/jekyll-theme-hamilton  # ...this is the workaround.
skin: daylight

# Default global variables for every post, see
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      math: true  # enables MathJax on pages.

# Files to exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site/
